// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgzakdvagkaalbhoqzqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnemFrZHZhZ2thYWxiaG9xenFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1OTc1NTcsImV4cCI6MjA3NTE3MzU1N30.mpXWHklvzLLUokJ1uNBNT-tmbr6yv4hWHXJnZ5r3FNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});